### ISSUE TITLE
Does not work selectable prop on the "Table" component.

### ISSUE THREAD

**Issue by dmitriy-modelic** [bigcommerce/big-design#1144] opened 2023-02-27 15:45 UTC
**Describe the bug**
I've tried to implement a selectable prop feature on the table component, it does select products from the table, but there are several issues:
1. Checkbox does not work on the selected items. It's always empty;
2. You can select any product multiple times and it will be pushed to the array of items so I can have any amount of the same item in the array;
3. "Unselect" function does not work. See item (2). Instead of unselect it adds the same item to the selected items array

We have more than 1500 items in our BC store, so we use all the table's features such as sortable and pagination, if that makes sense.
I've also tried to use StatefulTable component instead. The select feature works just fine. But I have not found a way to display all of the store products, since there's an API limit of 250. So I got back to just Table component.

**To Reproduce**
1. Use Table component.
2. Enable "selectable" prop with appropriate state.
3. Try to select items.

**Expected behavior**
I just want a selectable feature to work as in example here https://developer.bigcommerce.com/big-design/table?props=selectable&implementation=selectable
I need to select multiple products and make a bulk editing.

**Screenshots**
As you can see on the screenshots I was able to select same product 3 times and checkbox always empty.
<img width="1232" alt="s1" src="https://user-images.githubusercontent.com/116915087/221608454-0c8963e3-3692-4886-904b-defaa7351617.png">
<img width="958" alt="s2" src="https://user-images.githubusercontent.com/116915087/221608464-0bc0e635-301f-4c3a-b425-ce8b23ef59d9.png">

**Desktop (please complete the following information, if applicable):**
 - OS: Mac OS
 - Browser: Chrome

**Additional context**
My deps:
<img width="646" alt="image" src="https://user-images.githubusercontent.com/116915087/221609960-475de597-1c46-4331-8b6d-80c905a972a9.png">

Here is the "Table" code:
`<Table
  columns={[
          { header: 'Product name', hash: 'name', render: ({ id, name }) => renderName(id, name), isSortable: true },
          { header: 'SKU', hash: 'sku', render: ({sku}) => renderSku(sku), isSortable: false },
          { header: 'Stock', hash: 'stock', render: ({ stock }) => renderStock(stock), isSortable: true },
          { header: 'Price', hash: 'price', render: ({ price }) => renderPrice(price), isSortable: true },
          { header: 'Action', hideHeader: true, hash: 'id', render: ({ id }) => renderAction(id) },
        ]}
        items={tableItems}
        itemName="Products"
        keyField="sku"
        selectable={{
          selectedItems,
          onSelectionChange: setSelectedItems,
        }}
        pagination={{
          currentPage,
          totalItems: meta?.pagination?.total,
          onPageChange: setCurrentPage,
          itemsPerPageOptions,
          onItemsPerPageChange,
          itemsPerPage,
        }}
        sortable={{
          columnHash,
          direction,
          onSort,
        }}
        stickyHeader
      />`

Here is a simple state as in example:
`const [selectedItems, setSelectedItems] = useState([]);`

**Comment by chanceaclark** [comment] 2023-02-27 16:13
Hey @dmitriy-modelic, would you mind building a CodeSandbox example so we can explore the problem further? That would be extremely helpful for us to replicate the issue!

>I've also tried to use StatefulTable component instead.

The `StatefulTable` is primarily used for a known amount of data (in-memory). It's not useful at al for dynamic data, such as data returned from an API.

**Comment by dmitriy-modelic** [comment] 2023-02-27 16:32
Hey @chanceaclark ! For sure.

**Comment by dmitriy-modelic** [comment] 2023-02-27 16:50
@chanceaclark Here is a CodeSandbox with my table basics. I have not installed all the deps and the folder structure is different on my project. But I hope it should be enough for you to replicate the issue. Thank you!
https://codesandbox.io/s/eloquent-brahmagupta-5bdyh3?file=/src/App.js

**Comment by chanceaclark** [comment] 2023-02-27 17:34
@dmitriy-modelic would you mind also providing how you fetch products within `useProductList`? I have a feeling that the issue you are running into is that you are creating multiple references of the same product which is why you would see 3 of the same. I could be wrong, but understanding how `useProductList` and looking more at React Dev Tools to see how the component rerenders will be crucial to understand why.

**Comment by dmitriy-modelic** [comment] 2023-02-27 17:36
@chanceaclark It's here https://codesandbox.io/s/eloquent-brahmagupta-5bdyh3?file=/hooks/hooks.js

**Comment by dmitriy-modelic** [comment] 2023-02-27 17:48
@chanceaclark You see, the statefultable works just fine with my `useProductList`
<img width="569" alt="image" src="https://user-images.githubusercontent.com/116915087/221642873-036cddcf-9a0d-4b32-a48a-2e0afa7f0c77.png">

I understood that it's not my option, so want to figure out what's wrong with my "Table"...

**Comment by chanceaclark** [comment] 2023-02-27 19:34
>I have a feeling that the issue you are running into is that you are creating multiple references of the same product which is why you would see 3 of the same.

As per my [previous comment](https://github.com/bigcommerce/big-design/issues/1144#issuecomment-1446753828), I believe this is where the issue lies. However, I can't fully replicate this as that CodeSandbox is not entirely giving me a full perspective into the issue. Can you try and replicate what's happening on your end within that CodeSandbox (with just mocked data)?

**Comment by dmitriy-modelic** [comment] 2023-02-28 10:56
@chanceaclark Look, even without a fetcher function, with a testing products list, it does not work :(
https://codesandbox.io/s/eloquent-brahmagupta-5bdyh3?file=/src/App.js

**Comment by chanceaclark** [comment] 2023-02-28 15:05
@dmitriy-modelic, add this code into your example and you'll notice that everytime you select a row, it generates a new list of items.:
```tsx
  useEffect(() => {
    console.log(tableItems);
  }, [tableItems]);
```

That's what I was mentioning here:
>I have a feeling that the issue you are running into is that you are creating multiple references of the same product which is why you would see 3 of the same.

You can quick-fix it by wrapping the `.map` in a `useMemo` to show that it'll work as intended but that won't entirely fix your problem. You'll have to figure out how to make sure you are not generating new references for your tables `items` prop.

```tsx
  const tableItems = useMemo(
    () =>
      items.map(({ id, inventory_level: stock, name, price, sku }) => ({
        id,
        name,
        price,
        stock,
        sku,
      })),
    []
  );
```

Since this isn't an issue with our `Table` component, I will close this issue later today.

**Comment by dmitriy-modelic** [comment] 2023-02-28 15:21
Thank you for your helpful tips @chanceaclark ! Hope this will help me to fix this.

**Comment by chanceaclark** [comment] 2023-02-28 16:47
>When I select an item on the first page, for example, then go to the second page and go back to the first one, the selection is no longer shown. But it's still in the array of selected items. Can you suggest me how to fix this behaviour?

I can't fully provide a solution for you, but keep in mind that `selectedItems` is an array of JS references. When you select a row, it throws that rows reference into the state. For example, we show the row being selected by checking if the references are the same:
```ts
const item1 = { id: 1 };
const item2 = { id: 1 };

// Even though they have the same structure and data, they are both separate references.
console.log(item1 === item2) // false

const item3 = item1;

// Since you assign by reference, this will now be true
console.log(item1 === item3) // true
```
With that being said, you'll need to follow my suggestion above:
>You'll have to figure out how to make sure you are not generating new references for your tables' `items` prop.

---

>Probably you have some examples of the Table component implementation with the "selectable" and "pagination" features in use?

We currently don't have any async examples, but I do know it's possible since we have a few UI's in BC's control panel using it.

**Comment by dmitriy-modelic** [comment] 2023-02-28 16:54
Thank you! @chanceaclark

**Closed** 2023-03-01 15:34 UTC
Labels: wontfix
