### ISSUE TITLE
Change label prop in Selects to accept a FormControlLabel

### ISSUE THREAD

**Issue by jorgemoya** [bigcommerce/big-design#421] opened 2020-07-27 15:27 UTC
**Describe the solution, feature, or improvement you'd like**
Right now, the `label` prop only accepts a `string`. Need to change it to accept a `FormControlLabel` just like `Inputs`.

**Comment by chanceaclark** [comment] 2020-07-27 15:30
Closing, duplicate of #355.

**Closed by chanceaclark** 2020-07-27 15:30 UTC
